version: "3.10"
services:
  zebralint:
    build: .
    image: texlinter
    # Change local path to whichever local directory you want to read the tex files from and also save them
    volumes: [path-to-local-folder:/home/app/tex]
    stdin_open: true
    tty: true